# Generated by Django 5.2.6 on 2025-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'SuperUser'), (1, 'User')], null=True),
        ),
    ]
